stages:
  - build

# Build Job for the Server Module
build_server:
  stage: build
  script:
    - echo "Building the server module..."
    - cd core/server
    - mvn clean install
  artifacts:
    paths:
      - core/server/target
    expire_in: 40 week
  only:
    - main
    - develop

# Build Job for the Device Module
build_device:
  stage: build
  script:
    - echo "Building the device module..."
    - cd core/device
    - mvn clean install
  artifacts:
    paths:
      - core/device/target
    expire_in: 40 week
  only:
    - main
    - develop
    - Fixed-maybe

