variables:
  MAVEN_OPTS: "-Xmx1024m"
stages:
  - build
  - test

build_job:
  stage: build
  image: maven:3.9.4-eclipse-temurin-21
  script:
    - echo "Building the project..."
    - mvn clean package --batch-mode --fail-at-end
    #- echo "Current working directory:"
    #- pwd
    #- mvn clean test --batch-mode --fail-at-end
    - echo "Build job complete."
  #coverage: '/Coverage:\s+(\d+\.\d+)%/'
  artifacts:
    paths:
      - Device
      - Server
    expire_in: 40 week  # Artifacts will expire in 40 weeks
  only:
    - main
    - develop

test_job:
  stage: test
  image: maven:3.9.4-eclipse-temurin-21
  coverage: '/Coverage:\s+(\d+\.\d+)%/'
  artifacts:
    paths:
      - Device
      - Server
    expire_in: 40 week
  script:
    - cd Device/Communicator

    - mvn clean test jacoco:report
    - echo "Parsing coverage from target/site/jacoco/jacoco.xml..."
    - |
      coverageVal=$(xmllint --xpath "
        sum(//counter[@type='INSTRUCTION']/@covered) div
        ( sum(//counter[@type='INSTRUCTION']/@covered) + sum(//counter[@type='INSTRUCTION']/@missed) ) * 100
      " target/site/jacoco/jacoco.xml)
      echo "Coverage: ${coverageVal}%"
  only:
    - main
    - develop