
services:
  app:
    build: .
    ports:
      - "8080:8080"
      #- "8443:8443"
    #volumes:
    #  - .:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: benutzername
      SPRING_DATASOURCE_PASSWORD: passwort
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: benutzername
      MYSQL_PASSWORD: passwort
      MYSQL_ROOT_PASSWORD: passwort
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    driver: bridge