
services:
  app:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - ./src/main/resources/keystore.p12:/app/keystore.p12 #Mapping the Keystore to the container
    #  - .:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: benutzername
      SPRING_DATASOURCE_PASSWORD: passwort

      #HTTPS Config
      #SERVER_SSL_KEY_STORE: /app/keystore.p12
      #SERVER_SSL_KEY_STORE_PASSWORD: passwort
      #SERVER_SSL_KEY_STORE_TYPE: PKCS12
      #SERVER_PORT: 8443
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:11.5
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: benutzername
      MYSQL_PASSWORD: passwort
      MYSQL_ROOT_PASSWORD: passwort
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=passwort"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:

networks:
  app-network:
    driver: bridge