spring.jpa.hibernate.ddl-auto=update

#HTTPS Config
server.port=8080
ssl.certificate.path=/app/certs/server_cert.pem

#troubleshooting
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type=trace
logging.level.org.springframework.orm.jpa=debug
logging.level.root=DEBUG
logging.level.service=DEBUG

#openssl pkcs12 -export -in server_cert.pem -inkey server.key -out keystore.p12 -name myapp -password pass:deinPasswort
# Neues Zertifikat mit SAN:
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server_cert.pem -subj "/CN=server-app" -addext "subjectAltName=DNS:server-app"
openssl pkcs12 -export -in server_cert.pem -inkey server.key -out keystore.p12 -name server-app -password pass:password
