# Application name
spring.application.name=simulated-device

# Server port
server.port=8443

# HTTPS Configuration (ensure these match your actual keystore settings)
# server.ssl.key-store=/app/keystore.p12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=passwort
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

# Logging for troubleshooting
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type=trace
logging.level.org.springframework.orm.jpa=debug