spring.jpa.hibernate.ddl-auto=update

#HTTPS Config
server.port=8080
ssl.certificate.path=/app/certs/server_cert.pem


#troubleshooting
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type=trace
logging.level.org.springframework.orm.jpa=debug
logging.level.root=DEBUG
logging.level.service=DEBUG
docker logs jolly_moore


