spring.jpa.hibernate.ddl-auto=update

#HTTPS Config
server.port=8080

# CommunicatorService-specific URLs
communicator.backend.url=https://132.231.4.227:8443/agents
communicator.updater.url=http://updater:9090/update-image
communicator.led.url=http://led:6060/led


#troubleshooting
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type=trace
logging.level.org.springframework.orm.jpa=debug
logging.level.root=DEBUG
logging.level.service=DEBUG


