version: "3.9"

services:
  communicator:
    build: .
    container_name: communicator
    networks:
      - server_app-network
    volumes:
      - ./src/main/resources/certs/server_cert.pem:/app/certs/server_cert.pem
    restart: always

networks:
  server_app-network:
    external: true
