version: "3.9"

services:
  communicator:
    build: .
    container_name: communicator
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true  # Nutzt das vom Server erstellte Netzwerk
